import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _translations = {
    'en': {
      'discover_title': 'Discover',
      'discover_subtitle': 'Find a new pet for you',
      'see_more': 'See more',
      'your_pets': 'Your pets',
      'pet_care_nearby': 'Pet care nearby',
      'login': 'Login',
      'signup': 'Sign up',
      'login_as_guest': 'Continue as guest',
      'forgot_password': 'Forgot password?',
      'settings': 'Settings',
      'dashboard': 'Dashboard',
      'dashboard_greeting': "Stay on top of your pets",
      'my_pets': 'My pets',
      'care_plan': 'Care plan',
      'care_planner': 'Care planner',
      'care_planner_subtitle': 'Craft a calm day with hydration, walks, and meals',
      'planner_today': 'Today\'s plan',
      'upcoming': 'Upcoming',
      'view_all': 'View all',
      'dark_mode': 'Dark mode',
      'language': 'Language',
      'primary_color': 'Primary color',
      'compare': 'Compare',
      'adopt': 'Adopt',
      'ai_info': 'AI info',
      'catalog': 'Catalog',
      'profile': 'Profile',
      'home': 'Home',
      'get_started': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'confirm_password': 'Confirm password',
      'guest_hint': 'Browse quickly without account',
      'compare_hint': 'Select at least 2 pets to compare.',
      'favorites': 'Favorites',
      'care_tips': 'Care tips',
      'reminders': 'Reminders',
      'adoption_requests': 'Adoption requests',
      'adoption_status': 'Adoption status',
      'service_details': 'Service details',
      'services': 'Services',
      'health_records': 'Health records',
      'empty_health': 'No health records yet',
      'training': 'Training',
      'empty_training': 'No training tasks yet',
      'help_center': 'Help center',
      'search_help': 'Search help & FAQs',
      'contact_support': 'Contact support',
      'contact_support_body': 'We are here to help. Expect a response within a few hours.',
      'empty_faq': 'No help articles found',
      'done': 'Done',
      'empty_requests': 'No requests yet',
      'empty_favorites': 'No favorites saved',
      'empty_reminders': 'No reminders yet',
      'empty_tips': 'No tips available',
      'quick_actions': 'Quick actions',
      'search_pets': 'Search pets',
      'upcoming_reminders': 'Upcoming reminders',
      'latest_requests': 'Latest requests',
      'care_highlights': 'Care highlights',
      'mark_done': 'Mark done',
      'no_note': 'No note yet',
      'submitted_on': 'Submitted on',
      'mark_reviewed': 'Mark reviewed',
      'remove': 'Remove',
      'all': 'All',
      'note_optional': 'Note for shelter (optional)',
      'request_submitted': 'Request submitted',
      'cancel': 'Cancel',
      'submit': 'Submit',
      'age': 'Age',
      'weight': 'Weight',
      'distance': 'Distance',
      'rating_label': 'Rating',
      'ai_placeholder': 'AI-powered explanation will be here later',
      'close': 'Close',
      'adoption_note_for': 'Send an adoption note for',
      'book_service': 'Book service',
      'added_to_plan': 'Added to plan',
      'pending': 'Pending',
      'reviewed': 'Reviewed',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all read',
      'empty_notifications': 'You are all caught up',
      'mark_read': 'Mark read',
      'new': 'New',
      'achievements': 'Achievements',
      'achievements_subtitle': 'Track badges and celebrate progress',
      'achievements_hint': 'Boost a badge to unlock rewards faster.',
      'reward_label': 'Reward: {0}',
      'boost': 'Boost',
      'claim': 'Claim',
      'completed': 'Completed',
      'timeline': 'Timeline',
      'gallery': 'Gallery',
      'journal': 'Journal',
      'journal_recent': 'Recent journal',
      'add_entry': 'Add entry',
      'pet_name_hint': 'Pet name',
      'title': 'Title',
      'notes_hint': 'Notes',
      'mood': 'Mood',
      'unknown_pet': 'Unknown pet',
      'untitled': 'Untitled',
      'save': 'Save',
      'empty_journal': 'No journal entries yet',
      'just_now': 'Just now',
      'minutes_ago': 'm ago',
      'hours_ago': 'h ago',
      'days_ago': 'd ago',
      'add_quick_task': 'Add quick task',
      'quick_add': 'Quick add',
      'what_to_plan': 'What do you want to plan?',
      'added_quickly': 'Added from quick add',
      'save_plan': 'Save plan',
      'mark_undone': 'Mark undone',
      'supplies': 'Supplies',
      'supplies_low': 'Supplies & stock',
      'low_stock': 'Low stock',
      'all_stock_ok': 'Everything is stocked',
      'emergency_ready': 'Emergency ready',
      'emergency_description': 'Save checklists and hotlines for stressful moments.',
      'open_guide': 'Open guide',
      'hotline_label': 'Hotline: {number}',
    },
    'ar': {
      'discover_title': 'اكتشف',
      'discover_subtitle': 'ابحث عن حيوان أليف مناسب لك',
      'see_more': 'عرض المزيد',
      'your_pets': 'حيواناتك الأليفة',
      'pet_care_nearby': 'خدمات رعاية قريبة',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'login_as_guest': 'المتابعة كضيف',
      'forgot_password': 'نسيت كلمة المرور؟',
      'settings': 'الإعدادات',
      'dashboard': 'لوحة القيادة',
      'dashboard_greeting': 'تابع رعاية حيواناتك',
      'my_pets': 'حيواناتي',
      'care_plan': 'خطة العناية',
      'care_planner': 'مخطط العناية',
      'care_planner_subtitle': 'صمم يومًا هادئًا بالترطيب والمشي والوجبات',
      'planner_today': 'خطة اليوم',
      'upcoming': 'القادم',
      'view_all': 'عرض الكل',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'primary_color': 'اللون الرئيسي',
      'compare': 'مقارنة',
      'adopt': 'تبنّي',
      'ai_info': 'معلومات بالذكاء الاصطناعي',
      'catalog': 'الفهرس',
      'profile': 'الملف الشخصي',
      'home': 'الرئيسية',
      'get_started': 'ابدأ',
      'next': 'التالي',
      'skip': 'تخطي',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'confirm_password': 'تأكيد كلمة المرور',
      'guest_hint': 'تصفح سريع دون حساب',
      'compare_hint': 'اختر حيوانين على الأقل للمقارنة.',
      'favorites': 'المفضلة',
      'care_tips': 'نصائح العناية',
      'reminders': 'التذكيرات',
      'adoption_requests': 'طلبات التبني',
      'adoption_status': 'حالة التبني',
      'service_details': 'تفاصيل الخدمة',
      'services': 'الخدمات',
      'health_records': 'سجل الصحة',
      'empty_health': 'لا توجد سجلات صحية',
      'training': 'التدريب',
      'empty_training': 'لا توجد مهام تدريبية',
      'help_center': 'مركز المساعدة',
      'search_help': 'ابحث في المساعدة والأسئلة',
      'contact_support': 'تواصل مع الدعم',
      'contact_support_body': 'نحن هنا للمساعدة. سنرد خلال بضع ساعات.',
      'empty_faq': 'لا توجد مقالات مساعدة',
      'done': 'تم',
      'empty_requests': 'لا توجد طلبات بعد',
      'empty_favorites': 'لا توجد مفضلة محفوظة',
      'empty_reminders': 'لا توجد تذكيرات حالياً',
      'empty_tips': 'لا توجد نصائح متاحة',
      'quick_actions': 'إجراءات سريعة',
      'search_pets': 'ابحث عن حيوان',
      'upcoming_reminders': 'التذكيرات القادمة',
      'latest_requests': 'أحدث الطلبات',
      'care_highlights': 'أبرز نصائح العناية',
      'mark_done': 'وضع كمكتمل',
      'no_note': 'لا يوجد ملاحظة',
      'submitted_on': 'تم التقديم في',
      'mark_reviewed': 'وضع كمراجَع',
      'remove': 'حذف',
      'all': 'الكل',
      'note_optional': 'ملاحظة للمأوى (اختياري)',
      'request_submitted': 'تم إرسال الطلب',
      'cancel': 'إلغاء',
      'submit': 'إرسال',
      'age': 'العمر',
      'weight': 'الوزن',
      'distance': 'المسافة',
      'rating_label': 'التقييم',
      'ai_placeholder': 'سيتم إضافة شرح بالذكاء الاصطناعي لاحقًا',
      'close': 'إغلاق',
      'adoption_note_for': 'أرسل ملاحظة تبنٍ لـ',
      'book_service': 'احجز الخدمة',
      'added_to_plan': 'تمت الإضافة للخطة',
      'pending': 'قيد الانتظار',
      'reviewed': 'تمت المراجعة',
      'notifications': 'الإشعارات',
      'mark_all_read': 'تحديد الكل كمقروء',
      'empty_notifications': 'لا توجد إشعارات جديدة',
      'mark_read': 'تحديد كمقروء',
      'new': 'جديد',
      'achievements': 'الإنجازات',
      'achievements_subtitle': 'تتبع الشارات واحتفل بالتقدم',
      'achievements_hint': 'ادعم الشارة لفتح المكافآت أسرع.',
      'reward_label': 'المكافأة: {0}',
      'boost': 'تعزيز',
      'claim': 'استلام',
      'completed': 'مكتمل',
      'timeline': 'الخط الزمني',
      'gallery': 'المعرض',
      'journal': 'المفكرة',
      'journal_recent': 'آخر الملاحظات',
      'add_entry': 'إضافة ملاحظة',
      'pet_name_hint': 'اسم الحيوان',
      'title': 'العنوان',
      'notes_hint': 'ملاحظات',
      'mood': 'المزاج',
      'unknown_pet': 'حيوان غير معروف',
      'untitled': 'بدون عنوان',
      'save': 'حفظ',
      'empty_journal': 'لا توجد ملاحظات بعد',
      'just_now': 'الآن',
      'minutes_ago': 'دقائق مضت',
      'hours_ago': 'ساعات مضت',
      'days_ago': 'أيام مضت',
      'add_quick_task': 'إضافة مهمة سريعة',
      'quick_add': 'إضافة سريعة',
      'what_to_plan': 'ماذا تريد أن تخطط؟',
      'added_quickly': 'أضيفت من الإضافة السريعة',
      'save_plan': 'حفظ الخطة',
      'mark_undone': 'إلغاء الإنجاز',
      'supplies': 'المستلزمات',
      'supplies_low': 'المستلزمات والمخزون',
      'low_stock': 'المخزون منخفض',
      'all_stock_ok': 'كل شيء متوفر',
      'emergency_ready': 'الجاهزية للطوارئ',
      'emergency_description': 'احتفظ بالقوائم وأرقام الطوارئ للحظات الحرجة.',
      'open_guide': 'فتح الدليل',
      'hotline_label': 'خط الطوارئ: {number}',
    }
  };

  String t(String key, {List<String>? args, Map<String, String>? namedArgs}) {
    var value = _translations[locale.languageCode]?[key] ?? _translations['en']![key] ?? key;
    if (args != null && args.isNotEmpty) {
      for (var i = 0; i < args.length; i++) {
        value = value.replaceAll('{$i}', args[i]);
      }
    }
    if (namedArgs != null && namedArgs.isNotEmpty) {
      namedArgs.forEach((placeholder, replacement) {
        value = value.replaceAll('{$placeholder}', replacement);
      });
    }
    return value;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate old) => false;
}
